openapi: 3.0.3
info:
  title: Weather
  description: |-
    This is a back-end to check the weather.
  contact:
    email: mfranchi@fi.uba.ar
  version: 0.1.0
externalDocs:
  description: Find out more about Weather checker
  url: https://github.com/EugeniaFranchi/weather-back
tags:
  - name: weather
    description: Everything about the weather
paths:
  /v1:
    get:
      tags: [weather]
      description: Base endpoint
      responses:
        '200':
          description: Successful response
  /v1/location:
    get:
      tags: [weather]
      description: Returns the location of the client by it's IP
      responses:
        '200':
          description: Successful response
        '500':
          description: Location not found
  /v1/current/{city}:
    get:
      tags: [weather]
      description: Returns the current weather of the location client. 
                    If 'city' is specified, it returns the weather in that city.
      parameters:
        - in: path
          name: city
          schema:
            type: string
          required: false
          description: Name of a city
      responses:
        '200':
          description: Successful response
        '500':
          description: Location not found